language: bash
services: docker

env:
  - BASE_IMAGE_TAG=7.1.7-fpm
  - BASE_IMAGE_TAG=7.0.21-fpm

before_script:
  - env | sort
  - image="fesor/php:$BASE_IMAGE_TAG-onbuild"

script:
  - cat Dockerfile.source | envsubst "\$BASE_IMAGE_TAG" > Dockerfile
  - docker build -t $image .

after_success:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASS"
  - docker push $image
